apiVersion: apps/v1
kind: Deployment
metadata:
  name: openkrait
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openkrait
  template:
    metadata:
      labels:
        app: openkrait
    spec:
      containers:
      - name: openkrait
        image: your-username/openkrait:1.0.0
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-secret
              key: token
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
type: Opaque
data:
  token: <base64-encoded-vault-token>
