#!/usr/bin/env python3
import sys
import os

# Указываем путь к src/cli.py относительно этого файла
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))
from cli import main

if __name__ == "__main__":
    main()