name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

smoke-k8s:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: medyagh/setup-minikube@latest   
    - run: minikube start --driver=docker
    - run: kubectl apply -f examples/bad.yaml
    - run: |
        docker build -t openkrait:test .
        docker run --rm -v $HOME/.kube:/root/.kube:ro openkrait:test \
            scan --context minikube --namespace default    