name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #- name: Run tests
    #  run: pytest

  smoke-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker
    - name: Deploy vulnerable pod
      run: |
        # Создаем bad.yaml на лету, если забыли положить в репу
        cat <<EOF > bad.yaml
        apiVersion: v1
        kind: Pod
        metadata:
          name: bad-pod
        spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
        EOF
        kubectl apply -f bad.yaml
    - name: Build and Test Scanner
      run: |
        docker build -t openkrait:test .
        docker run --rm -v $HOME/.kube:/root/.kube:ro openkrait:test openkrait scan-k8s
