---
name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  smoke-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker
          kubernetes-version: v1.26.0
      - name: Verify Minikube setup
        run: |
          minikube status
          kubectl cluster-info
          kubectl get nodes
      - name: Deploy vulnerable pod
        run: |
          cat <<EOF > bad.yaml
          apiVersion: v1
          kind: Pod
          metadata:
            name: bad-pod
            namespace: default
          spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              imagePullPolicy: IfNotPresent
          EOF

          kubectl apply -f bad.yaml --validate=false
          sleep 20
          kubectl get pods -o wide
      - name: Build Docker image
        run: |
          docker build -t openkrait:test .
      - name: Prepare kubeconfig for container
        run: >
          # СОЗДАЕМ KUBECONFIG С ПРАВИЛЬНЫМИ ПУТЯМИ ДЛЯ КОНТЕЙНЕРА

          # Основная проблема: пути в kubeconfig ведут на хост, а не в контейнер

          mkdir -p ~/.kube

          kubectl config view --flatten > ~/.kube/config-original


          # Заменяем абсолютные пути на относительные

          sed 's|/home/runner/.minikube|/tmp/.minikube|g' ~/.kube/config-original > ~/.kube/config-container


          # Создаем директорию для монтирования

          mkdir -p /tmp/.minikube

          cp -r ~/.minikube/* /tmp/.minikube/
      - name: Test Kubernetes Scanner
        run: |+
          echo "Запуск сканера OpenKrait..."
          docker run --rm \
            -v /tmp/.minikube:/tmp/.minikube:ro \
            -v ~/.kube/config-container:/home/myuser/.kube/config:ro \
            openkrait:test openkrait scan-k8s
            
      - name: Verify scan results
        run: |
          output=$(docker run --rm \
            -v /tmp/.minikube:/tmp/.minikube:ro \
            -v ~/.kube/config-container:/home/myuser/.kube/config:ro \
            openkrait:test openkrait scan-k8s 2>&1)

          echo "Scan output:"
          echo "$output"

          if echo "$output" | grep -q "nginx:1\.14"; then
            echo "✅ Уязвимость обнаружена"
          else
            echo "❌ Уязвимость не обнаружена"
            exit 1
          fi
